name: Notify Discord on Push

on:
  push:
    branches:
      - dev

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for package changes
        id: check
        run: |
          if git diff --name-only HEAD^ HEAD | grep -E "package(-lock)?\.json"; then
            echo "npm_install=true" >> $GITHUB_ENV
          else
            echo "npm_install=false" >> $GITHUB_ENV
          fi

      - name: Send notification to Discord
        run: |
          if [ "$npm_install" == "true" ]; then
            INSTALL_MSG="\nТакож виконайте команду: \`npm install\`"
          else
            INSTALL_MSG=""
          fi
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"Я вніс зміни в гілку **dev**. Будь ласка, перед продовженням роботи збережіть і оновіть свої гілки:\n\`\`\`\ngit add .\ngit commit -m \\\"Ваш коміт\\\"\ngit checkout dev\ngit pull origin dev\ngit checkout ваша-гілка\ngit merge dev\n\`\`\`$INSTALL_MSG\"}" \
          "${{ secrets.DISCORD_WEBHOOK_URL }}"
